Corrige la taxe aurifère suite à l'évolution des entités
openfisca/openfisca-france-fiscalite-miniere pull request #26
Opened 2022-06-13 21:30 UTC by sandcha

* Correction d'un crash.
* Périodes concernées : à partir du 01/01/2020.
* Zones impactées : `chemin/vers/le/fichier/contenant/les/variables/impactées`.
* Détails :
  - Description de la fonctionnalité ajoutée ou du nouveau comportement adopté.
  - Cas dans lesquels une erreur était constatée.

- - - -

Ces changements :

- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france-fiscalite-miniere/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france-fiscalite-miniere/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france-fiscalite-miniere/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france-fiscalite-miniere/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

2022-06-13 21:43 UTC, sandcha commented on openfisca_france_fiscalite_miniere/tests/test_taxe_aurifere.yaml
> +        surface_totale: 1
@vmaubert Indiquer la surface_totale comme une donnée du titre aurait plus de sens, non ?

2022-06-14 07:35 UTC, vmaubert commented on openfisca_france_fiscalite_miniere/tests/test_taxe_aurifere.yaml
> +        surface_totale: 1
oui tu as raison @sandcha 👍

2022-06-15 13:37 UTC, MichaelBitard requested changes
Attention, tu à ouvert la PR vers fix-taxe-or et pas vers master, c'est normal ?

Aussi, il faudrait incrémenter la version de OpenFisca-France-Fiscalite-Miniere

Vu que c'est un bugfix, une 3.1.0 semble bien, qu'en penses-tu ? C'est ligne 5 dans le fichier setup.py

2022-06-20 07:37 UTC, sandcha commented
> Attention, tu as ouvert la PR vers fix-taxe-or et pas vers master, c'est normal ?

👍 Pour la branche de référence, c'était fait exprès pour que vous puissiez tester ^^ (on note d'ordinaire un warning dans la description de la PR pour que ce ne soit pas oublié).

> Aussi, il faudrait incrémenter la version de OpenFisca-France-Fiscalite-Miniere
> 
> Vu que c'est un bugfix, une 3.1.0 semble bien, qu'en penses-tu ? C'est ligne 5 dans le fichier setup.py

Le bump de version est fait post revue pour ne pas avoir à revenir dessus si une autre PR est mergée entre-temps et le  changelog reprend l'essentiel du descriptif de la PR. Mais il est vrai que ces conventions sont écrites nulle part. On pourrait les ajouter au CONTRIBUTING peut-être ? 🤔 

En l'état actuel de la PR qui ne modifie que la règle de calcul d'une formule, le versionnement serait plutôt en patch selon la [règle par défaut](https://openfisca.org/doc/contribute/semver.html) qui se base sur le fait que ça n'impacte pas l'interface de réutilisation du modèle. 
> Ceci dit, si on change la `surface_totale` de place / d'entité comme dit dans les commentaires plus haut, ce sera non rétro-compatible et donc un bump majeur.

2022-06-20 07:44 UTC, MichaelBitard commented
> > Attention, tu as ouvert la PR vers fix-taxe-or et pas vers master, c'est normal ?
> 
> +1 Pour la branche de référence, c'était fait exprès pour que vous puissiez tester ^^ (on note d'ordinaire un warning dans la description de la PR pour que ce ne soit pas oublié).

Merci pour l'info je ne savais pas

> 
> > Aussi, il faudrait incrémenter la version de OpenFisca-France-Fiscalite-Miniere
> > Vu que c'est un bugfix, une 3.1.0 semble bien, qu'en penses-tu ? C'est ligne 5 dans le fichier setup.py
> 
Oui 3.1.0 nickel !

> Le bump de version est fait post revue pour ne pas avoir à revenir dessus si une autre PR est mergée entre-temps et le changelog reprend l'essentiel du descriptif de la PR. Mais il est vrai que ces conventions sont écrites nulle part. On pourrait les ajouter au CONTRIBUTING peut-être ? thinking
> 
Oui en effet on pourrait faire ça, la chose étrange c'est que la PR ne peut pas passer tant que la version n'a pas été incrémentée, et ça me fait bizarre de relire des PR rouges (mais après, c'est parce que j'ai été habitué comme ça aussi)

> En l'état actuel de la PR qui ne modifie que la règle de calcul d'une formule, le versionnement serait plutôt en patch selon la [règle par défaut](https://openfisca.org/doc/contribute/semver.html) qui se base sur le fait que ça n'impacte pas l'interface de réutilisation du modèle.
> 
> > Ceci dit, si on change la `surface_totale` de place / d'entité comme dit dans les commentaires plus haut, ce sera non rétro-compatible et donc un bump majeur.

Bien vu !

2022-07-04 12:10 UTC, MichaelBitard approved these changes

2022-07-06 13:24 UTC, sandcha commented
Rebase en cours.

2022-07-06 13:44 UTC, merged