Corrige les règles de calcul des taxes et redevances
openfisca/openfisca-france-fiscalite-miniere pull request #4
Opened 2020-02-12 16:58 UTC by guillaumelevieux

* Correction d'un crash.
* Périodes concernées : toutes.
* Zones impactées : toutes.
* Détails :
  - Corrige les règles de calcul des taxes et redevances selon les taux et assiettes en vigueur par années d'imposition
- - - -

Ces changements (effacez les lignes ne correspondant pas à votre cas) :
- Corrigent ou améliorent un calcul déjà existant.

- - - -

Quelques conseils à prendre en compte :

- [ ] Jetez un coup d'œil au [guide de contribution](https://github.com/openfisca/openfisca-france-fiscalite-miniere/blob/master/CONTRIBUTING.md).
- [ ] Regardez s'il n'y a pas une [proposition introduisant ces mêmes changements](https://github.com/openfisca/openfisca-france-fiscalite-miniere/pulls).
- [ ] Documentez votre contribution avec des références législatives.
- [ ] Mettez à jour ou ajoutez des tests correspondant à votre contribution.
- [ ] Augmentez le [numéro de version](https://speakerdeck.com/mattisg/git-session-2-strategies?slide=81) dans [`setup.py`](https://github.com/openfisca/openfisca-france-fiscalite-miniere/blob/master/setup.py).
- [ ] Mettez à jour le [`CHANGELOG.md`](https://github.com/openfisca/openfisca-france-fiscalite-miniere/blob/master/CHANGELOG.md).
- [ ] Assurez-vous de bien décrire votre contribution, comme indiqué ci-dessus

Et surtout, n'hésitez pas à demander de l'aide ! :)

2020-02-12 17:01 UTC, guillaumelevieux commented
<script src="https://gist.github.com/guillaumelevieux/c0d6e2acc8b1a748b06b863ec15eb6f4.js"></script>

2020-02-13 10:30 UTC, benjello requested changes
@guillaumelevieux : il serait utile que tu rajoutes des tests qui ne passeraient pas dans la version antérieure.

@maukoquiroga : je ne comprends pas pourquoi le flake8 de circleci râle car cela passe sans problème en local chez moi.

2020-02-14 14:55 UTC, maukoquiroga commented
@benjello Car il y a des plugins sups.

2020-02-14 15:01 UTC, benjello commented
@maukoquiroga : et pourquoi ces plugins supplémentaires ne sont-ils pas pris en compte par circleci ? J'ai juste fait un 
```bash
make install 
```
en local.

2020-02-14 16:28 UTC, bonjourmauko approved these changes
Top !

2020-02-14 17:09 UTC, maukoquiroga commented
@benjello Si c'est le cas, effectivement il y a un problème ...

2020-02-17 10:24 UTC, benjello approved these changes

2020-02-17 10:24 UTC, benjello commented
@guillaumelevieux @maukoquiroga LGTM.

2020-02-20 10:11 UTC, merged